config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

    def index
        @members = Member.all
    end

    def new
        @member = Member.new
    end

    def create
        @member = Member.new(member_params)
        if @member.save
            redirect_to :action => "index"
        else
            redirect_to :action => "index"
        end
    end

    def show
        @member = Member.find(params[:id])
    end

    def edit 
        @member = Member.find(params[:id])
    end

    def update
        @member = Member.find(params[:id])
        if @member.update(member_params)
            redirect_to :action => "index"
        else
            redirect_to :action => "index"
        end
    end

    def destroy
        @member = Member.find(params[:id])
        @member.destroy
        redirect_to :action => "index"
    end


    private
    def member_params
        params.require(:member).permit(:name, :profile, :mentor, :grade)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekkobe2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<h1>編集</h1>
<div class="edit-container">
<%= form_for @member do |p| %>
    <div class="field">
    <%= p.label :名前 %>
    <%= p.text_field :name, :size => 30 %>
    <%= p.label :大学・学部 %>
    <%= p.text_field :profile, :size => 30 %>
    <%= p.label :メンター %>
    <%= p.text_field :mentor, :size => 30 %>
    <%= p.label :学年 %>
    <%= p.text_field :grade %>
    </div>
    <%= p.submit "編集" %>
<% end %>
<%= link_to "投稿一覧", members_path %>
</div>

app/views/members/index.html.erb
<h1>投稿一覧</h1>
<div class="all-container">
    <% @members.each do |p| %>
        <%= p.name %>
        <%= p.profile %>
        <%= p.mentor %>
        <%= p.grade %>
        <%= p.created_at %>
        <%= link_to "詳細", member_path(p.id) %>
    <% end %>
</div>
<%= link_to "新規投稿", new_member_path %>

app/views/members/new.html.erb
<h1>新規投稿</h1>
<div class="new-container">
<%= form_for @member do |p| %>
    <div class="field">
    <%= p.label :名前 %>
    <%= p.text_field :name, :size => 30 %>
    <%= p.label :大学・学部 %>
    <%= p.text_field :profile, :size => 30 %>
    <%= p.label :メンター %>
    <%= p.text_field :mentor, :size => 30 %>
    <%= p.label :学年 %>
    <%= p.text_field :grade %>
    </div>
    <%= p.submit "投稿" %>
<% end %>
<%= link_to "投稿一覧", members_path %>
</div>

app/views/members/show.html.erb
<h1>詳細</h1>
<div class="show-container">
    <%= @member.name %>
    <%= @member.mentor %>
    <%= @member.profile %>
    <%= @member.grade %>
    <%= @member.created_at %>
    <%= button_to "投稿削除", member_path(@member.id), method: :delete %>
    <%= link_to "編集", edit_member_path(@member.id) %>
</div>
<%= link_to "投稿一覧", members_path %>